// Generated by tools/office-addin/build.py from build_view_scripts.VIEWS. Do not edit by hand.
// Each view does what BOR_AddIn.xlam did: unprotect Orders, show A:DZ, hide the view's columns,
// protect again (drawing objects, contents, scenarios locked). Protect / Un-Protect act on the
// active sheet.
const VIEWS = {
    "Open Order": [
        "F:H",
        "P:AD",
        "AH:AO",
        "AQ:AS"
    ],
    "Confirmation": [
        "F:L",
        "S:AD",
        "AH:AO",
        "AQ:AS"
    ],
    "Invoice": [
        "F:H",
        "P:T",
        "W:AD",
        "AH:AO",
        "AQ:AS"
    ],
    "Bill of Lading": [
        "F:L",
        "P:T",
        "V:AD",
        "AH:AH",
        "AO:AO",
        "AQ:AS"
    ],
    "Documents": [
        "F:L",
        "P:T",
        "X:AD",
        "AH:AH",
        "AO:AS"
    ],
    "Payment": [
        "F:M",
        "P:T",
        "AC:AO"
    ],
    "Show All": []
};

async function applyView(name) {
    await Excel.run(async (context) => {
        const sheet = context.workbook.worksheets.getItemOrNullObject("Orders");
        await context.sync();
        if (sheet.isNullObject) {
            return; // not a mill order workbook
        }
        sheet.protection.load("protected");
        await context.sync();
        if (sheet.protection.protected) {
            sheet.protection.unprotect();
        }
        sheet.getRange("A:DZ").columnHidden = false;
        VIEWS[name].forEach((address) => {
            sheet.getRange(address).columnHidden = true;
        });
        sheet.activate();
        sheet.protection.protect({ allowEditObjects: false, allowEditScenarios: false });
        await context.sync();
    });
}

// Protect / Un-Protect, as BOR_AddIn.xlam's Protek_Motek: the active sheet, no password.
async function setProtection(on) {
    await Excel.run(async (context) => {
        const sheet = context.workbook.worksheets.getActiveWorksheet();
        sheet.protection.load("protected");
        await context.sync();
        if (on && !sheet.protection.protected) {
            sheet.protection.protect({ allowEditObjects: false, allowEditScenarios: false });
        } else if (!on && sheet.protection.protected) {
            sheet.protection.unprotect();
        }
        await context.sync();
    });
}

function command(label, run) {
    return async (event) => {
        try {
            await run();
        } catch (error) {
            console.error(`BOR ${label} failed`, error);
        }
        event.completed();
    };
}

Office.onReady(() => {});
Office.actions.associate("viewOpenOrder", command("Open Order", () => applyView("Open Order")));
Office.actions.associate("viewConfirmation", command("Confirmation", () => applyView("Confirmation")));
Office.actions.associate("viewInvoice", command("Invoice", () => applyView("Invoice")));
Office.actions.associate("viewBillOfLading", command("Bill of Lading", () => applyView("Bill of Lading")));
Office.actions.associate("viewDocuments", command("Documents", () => applyView("Documents")));
Office.actions.associate("viewPayment", command("Payment", () => applyView("Payment")));
Office.actions.associate("viewShowAll", command("Show All", () => applyView("Show All")));
Office.actions.associate("protectSheet", command("Protect", () => setProtection(true)));
Office.actions.associate("unprotectSheet", command("Un-Protect", () => setProtection(false)));
